// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mongod.proto

/*
Package mongod is a generated protocol buffer package.

It is generated from these files:
	proto/mongod.proto

It has these top-level messages:
	UpsertResult
	BoolField
	IDs
*/
package mongod

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpsertResult struct {
	Updated  uint32 `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
	Inserted uint32 `protobuf:"varint,2,opt,name=inserted" json:"inserted,omitempty"`
}

func (m *UpsertResult) Reset()                    { *m = UpsertResult{} }
func (m *UpsertResult) String() string            { return proto.CompactTextString(m) }
func (*UpsertResult) ProtoMessage()               {}
func (*UpsertResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpsertResult) GetUpdated() uint32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *UpsertResult) GetInserted() uint32 {
	if m != nil {
		return m.Inserted
	}
	return 0
}

type BoolField struct {
	Value  bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Ignore bool `protobuf:"varint,2,opt,name=ignore" json:"ignore,omitempty"`
}

func (m *BoolField) Reset()                    { *m = BoolField{} }
func (m *BoolField) String() string            { return proto.CompactTextString(m) }
func (*BoolField) ProtoMessage()               {}
func (*BoolField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BoolField) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *BoolField) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

type IDs struct {
	Id []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
}

func (m *IDs) Reset()                    { *m = IDs{} }
func (m *IDs) String() string            { return proto.CompactTextString(m) }
func (*IDs) ProtoMessage()               {}
func (*IDs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IDs) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*UpsertResult)(nil), "go_micro_pkg_mongod.UpsertResult")
	proto.RegisterType((*BoolField)(nil), "go_micro_pkg_mongod.BoolField")
	proto.RegisterType((*IDs)(nil), "go_micro_pkg_mongod.IDs")
}

func init() { proto.RegisterFile("proto/mongod.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcd, 0xcf, 0x4b, 0xcf, 0x4f, 0xd1, 0x03, 0x73, 0x84, 0x84, 0xd3, 0xf3, 0xe3,
	0x73, 0x33, 0x93, 0x8b, 0xf2, 0xe3, 0x0b, 0xb2, 0xd3, 0xe3, 0x21, 0x52, 0x4a, 0x2e, 0x5c, 0x3c,
	0xa1, 0x05, 0xc5, 0xa9, 0x45, 0x25, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x12, 0x5c, 0xec,
	0xa5, 0x05, 0x29, 0x89, 0x25, 0xa9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x30, 0xae,
	0x90, 0x14, 0x17, 0x47, 0x66, 0x1e, 0x48, 0x65, 0x6a, 0x8a, 0x04, 0x13, 0x58, 0x0a, 0xce, 0x57,
	0xb2, 0xe4, 0xe2, 0x74, 0xca, 0xcf, 0xcf, 0x71, 0xcb, 0x4c, 0xcd, 0x49, 0x11, 0x12, 0xe1, 0x62,
	0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x05, 0x1b, 0xc0, 0x11, 0x04, 0xe1, 0x08, 0x89, 0x71, 0xb1, 0x65,
	0xa6, 0xe7, 0xe5, 0x17, 0xa5, 0x82, 0x35, 0x73, 0x04, 0x41, 0x79, 0x4a, 0xa2, 0x5c, 0xcc, 0x9e,
	0x2e, 0xc5, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x20, 0x2b, 0x99, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53,
	0x9c, 0x38, 0xa2, 0xd8, 0x20, 0x2e, 0x4c, 0x62, 0x03, 0xbb, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xfe, 0x03, 0xd5, 0x1e, 0xd3, 0x00, 0x00, 0x00,
}
