// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mysql.proto

/*
Package mysql is a generated protocol buffer package.

It is generated from these files:
	proto/mysql.proto

It has these top-level messages:
	Pagination
	Sort
	UpsertResults
	DeleteResults
	IDs
	BoolField
*/
package mysql

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SortDirection will be used for transform incomming request into mysql sort statement.
type SortDirection int32

const (
	SortDirection_ASC  SortDirection = 0
	SortDirection_DESC SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var SortDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}
func (SortDirection) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Pagination contains all pagination variables.
type Pagination struct {
	Page    uint64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PerPage uint64 `protobuf:"varint,2,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pagination) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetPerPage() uint64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

// Sort contains fields for SQL order statement.
type Sort struct {
	Field     string        `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Direction SortDirection `protobuf:"varint,2,opt,name=direction,enum=go.micro.pkg.mysql.SortDirection" json:"direction,omitempty"`
}

func (m *Sort) Reset()                    { *m = Sort{} }
func (m *Sort) String() string            { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()               {}
func (*Sort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Sort) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Sort) GetDirection() SortDirection {
	if m != nil {
		return m.Direction
	}
	return SortDirection_ASC
}

// UpsertResult contains response for mysql upserts.
type UpsertResults struct {
	RowsAffected int64 `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected" json:"rows_affected,omitempty"`
	Updated      int64 `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
	Inserted     int64 `protobuf:"varint,3,opt,name=inserted" json:"inserted,omitempty"`
}

func (m *UpsertResults) Reset()                    { *m = UpsertResults{} }
func (m *UpsertResults) String() string            { return proto.CompactTextString(m) }
func (*UpsertResults) ProtoMessage()               {}
func (*UpsertResults) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpsertResults) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *UpsertResults) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *UpsertResults) GetInserted() int64 {
	if m != nil {
		return m.Inserted
	}
	return 0
}

// DeleteResults contains results when rows are deleted.
type DeleteResults struct {
	Deleted int64 `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteResults) Reset()                    { *m = DeleteResults{} }
func (m *DeleteResults) String() string            { return proto.CompactTextString(m) }
func (*DeleteResults) ProtoMessage()               {}
func (*DeleteResults) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteResults) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

// IDs is a commonly used data.
type IDs struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *IDs) Reset()                    { *m = IDs{} }
func (m *IDs) String() string            { return proto.CompactTextString(m) }
func (*IDs) ProtoMessage()               {}
func (*IDs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IDs) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

// BoolField contains data for boolean field.
type BoolField struct {
	Value  bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Ignore bool `protobuf:"varint,2,opt,name=ignore" json:"ignore,omitempty"`
}

func (m *BoolField) Reset()                    { *m = BoolField{} }
func (m *BoolField) String() string            { return proto.CompactTextString(m) }
func (*BoolField) ProtoMessage()               {}
func (*BoolField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BoolField) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *BoolField) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func init() {
	proto.RegisterType((*Pagination)(nil), "go.micro.pkg.mysql.Pagination")
	proto.RegisterType((*Sort)(nil), "go.micro.pkg.mysql.Sort")
	proto.RegisterType((*UpsertResults)(nil), "go.micro.pkg.mysql.UpsertResults")
	proto.RegisterType((*DeleteResults)(nil), "go.micro.pkg.mysql.DeleteResults")
	proto.RegisterType((*IDs)(nil), "go.micro.pkg.mysql.IDs")
	proto.RegisterType((*BoolField)(nil), "go.micro.pkg.mysql.BoolField")
	proto.RegisterEnum("go.micro.pkg.mysql.SortDirection", SortDirection_name, SortDirection_value)
}

func init() { proto.RegisterFile("proto/mysql.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x93, 0x36, 0xc9, 0x60, 0xa4, 0x0e, 0x45, 0xa3, 0xa7, 0x1a, 0x2f, 0xd5, 0x43,
	0x04, 0x3d, 0x89, 0x07, 0x69, 0x1b, 0x05, 0x6f, 0x65, 0x8b, 0x17, 0x41, 0x4a, 0x6c, 0xa6, 0x61,
	0x35, 0xcd, 0xc6, 0xdd, 0xad, 0xe2, 0xbf, 0x97, 0x6c, 0x1a, 0x45, 0xbc, 0xcd, 0xf7, 0xde, 0xce,
	0xcc, 0xee, 0x5b, 0xd8, 0xaf, 0xa4, 0xd0, 0xe2, 0x62, 0xfd, 0xa5, 0xde, 0x8b, 0xd8, 0xd4, 0x88,
	0xb9, 0x88, 0xd7, 0x7c, 0x29, 0x45, 0x5c, 0xbd, 0xe5, 0xb1, 0x71, 0xa2, 0x1b, 0x80, 0x59, 0x9a,
	0xf3, 0x32, 0xd5, 0x5c, 0x94, 0x88, 0xe0, 0x54, 0x69, 0x4e, 0xa1, 0x35, 0xb4, 0x46, 0x0e, 0x33,
	0x35, 0x1e, 0x81, 0x57, 0x91, 0x5c, 0x18, 0xbd, 0x63, 0x74, 0xb7, 0x22, 0x39, 0x4b, 0x73, 0x8a,
	0x9e, 0xc1, 0x99, 0x0b, 0xa9, 0x71, 0x00, 0xdd, 0x15, 0xa7, 0x22, 0x33, 0x7d, 0x3e, 0x6b, 0x00,
	0x6f, 0xc1, 0xcf, 0xb8, 0xa4, 0x65, 0x3d, 0xd9, 0x74, 0xee, 0x5d, 0x9e, 0xc4, 0xff, 0xaf, 0x10,
	0xd7, 0x23, 0x92, 0xf6, 0x20, 0xfb, 0xed, 0x89, 0x5e, 0x21, 0x78, 0xac, 0x14, 0x49, 0xcd, 0x48,
	0x6d, 0x0a, 0xad, 0xf0, 0x14, 0x02, 0x29, 0x3e, 0xd5, 0x22, 0x5d, 0xad, 0x68, 0xa9, 0xa9, 0xd9,
	0x67, 0xb3, 0xdd, 0x5a, 0x1c, 0x6f, 0x35, 0x0c, 0xc1, 0xdd, 0x54, 0x59, 0x5a, 0xdb, 0x1d, 0x63,
	0xb7, 0x88, 0xc7, 0xe0, 0xf1, 0xb2, 0x9e, 0x47, 0x59, 0x68, 0x1b, 0xeb, 0x87, 0xa3, 0x33, 0x08,
	0x12, 0x2a, 0x48, 0x53, 0xbb, 0x2b, 0x04, 0x37, 0x33, 0x42, 0xbb, 0xa5, 0xc5, 0xe8, 0x10, 0xec,
	0x87, 0x44, 0x61, 0x1f, 0x6c, 0x9e, 0xa9, 0xd0, 0x1a, 0xda, 0x23, 0x9f, 0xd5, 0x65, 0x74, 0x0d,
	0xfe, 0x44, 0x88, 0xe2, 0xde, 0xbc, 0x7e, 0x00, 0xdd, 0x8f, 0xb4, 0xd8, 0x34, 0x59, 0x7a, 0xac,
	0x01, 0x3c, 0x80, 0x1e, 0xcf, 0x4b, 0x21, 0x9b, 0x28, 0x3d, 0xb6, 0xa5, 0xf3, 0x08, 0x82, 0x3f,
	0x31, 0xa0, 0x0b, 0xf6, 0x78, 0x3e, 0xed, 0xef, 0xa0, 0x07, 0x4e, 0x72, 0x37, 0x9f, 0xf6, 0xad,
	0x89, 0xfb, 0xd4, 0x35, 0x81, 0xbd, 0xf4, 0xcc, 0x77, 0x5e, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x50, 0xa5, 0xe0, 0x65, 0xe3, 0x01, 0x00, 0x00,
}
